# Generated by Django 3.2.5 on 2022-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=255)),
                ('Contact', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
    ]
